/* Generated by build.py — do not edit by hand. Re-run the build instead. */
window.SITE_DATA = {
 "subjects": [
  {
   "id": "compiler-design",
   "title": "Compiler Design & Construction",
   "code": "CDC",
   "color": "#38bdf8",
   "monogram": "CD",
   "blurb": "Seven chapters from compiling fundamentals to code generation — plus a terminology dictionary, exam checklists and a chapter-wise question bank.",
   "src": "cdc.html",
   "sha": "20fa0eba9590",
   "url": "compiler-design/index.html",
   "groups": [
    {
     "name": "Chapters",
     "items": [
      {
       "id": "ch1",
       "title": "Chapter 1 — Introduction to Compiling"
      },
      {
       "id": "ch2",
       "title": "Chapter 2 — Simple One-Pass Compiler"
      },
      {
       "id": "ch3",
       "title": "Chapter 3 — Lexical Analysis"
      },
      {
       "id": "ch4",
       "title": "Chapter 4 — Syntax Analysis"
      },
      {
       "id": "ch5",
       "title": "Chapter 5 — Semantic Analysis"
      },
      {
       "id": "ch6",
       "title": "Chapter 6 — Intermediate Code"
      },
      {
       "id": "ch7",
       "title": "Chapter 7 — Code Generation and Optimizing"
      }
     ]
    },
    {
     "name": "Exam prep & revision",
     "items": [
      {
       "id": "dict",
       "title": "Compiler Terminology Dictionary"
      },
      {
       "id": "howto",
       "title": "How To Solve Compiler Design Problems — Exam Checklists"
      },
      {
       "id": "qbank",
       "title": "Chapter-Wise Practice Question Bank"
      },
      {
       "id": "revision",
       "title": "Rapid Revision"
      },
      {
       "id": "matrix",
       "title": "Final Syllabus Coverage Matrix"
      },
      {
       "id": "report",
       "title": "Final Quality Report"
      }
     ]
    }
   ]
  },
  {
   "id": "dbms",
   "title": "BIT 231 — Database Management System",
   "code": "DBMS",
   "color": "#3b82f6",
   "monogram": "DB",
   "blurb": "Twelve chapters covering the full BIT 231 syllabus — ER modelling, relational algebra, normalisation, SQL — with per-chapter VSQA / SQA / LQA banks, practice drills and a rapid-revision section.",
   "src": "DBMS.html",
   "sha": "1d4ea0c5bbd0",
   "url": "dbms/index.html",
   "groups": [
    {
     "name": "Chapters",
     "items": [
      {
       "id": "ch1",
       "title": "Chapter 1 — Introduction to Database Systems"
      },
      {
       "id": "ch2",
       "title": "Chapter 2 — The Relational Data Models"
      },
      {
       "id": "ch3",
       "title": "Chapter 3 — Relational Algebra & Calculus"
      },
      {
       "id": "ch4",
       "title": "Chapter 4 — SQL (High-Priority Chapter)"
      },
      {
       "id": "ch5",
       "title": "Chapter 5 — Conceptual Design"
      },
      {
       "id": "ch6",
       "title": "Chapter 6 — Logical Design"
      },
      {
       "id": "ch7",
       "title": "Chapter 7 — Normalization"
      },
      {
       "id": "ch8",
       "title": "Chapter 8 — Database Technology"
      },
      {
       "id": "ch9",
       "title": "Chapter 9 — Distributed Architecture"
      },
      {
       "id": "ch10",
       "title": "Chapter 10 — Database Evaluation and Transaction"
      },
      {
       "id": "ch11",
       "title": "Chapter 11 — Data Analysis"
      },
      {
       "id": "ch12",
       "title": "Chapter 12 — Database and the World Wide Web"
      }
     ]
    },
    {
     "name": "Practice drills",
     "items": [
      {
       "id": "sqlpractice",
       "title": "SQL Practice Section"
      },
      {
       "id": "rapractice",
       "title": "Relational Algebra Practice Section"
      },
      {
       "id": "normpractice",
       "title": "Normalization Practice Section"
      }
     ]
    },
    {
     "name": "Exam prep & revision",
     "items": [
      {
       "id": "revision",
       "title": "Final Master Revision — One-Day Revision"
      },
      {
       "id": "qbank",
       "title": "Final Question Bank — Chapter-wise (All 12 Chapters)"
      },
      {
       "id": "matrix",
       "title": "Master Syllabus Coverage Matrix"
      },
      {
       "id": "finalreport",
       "title": "Final Quality & Coverage Report"
      }
     ]
    }
   ]
  },
  {
   "id": "sad",
   "title": "System Analysis & Design",
   "code": "SAD",
   "color": "#14b8a6",
   "monogram": "SA",
   "blurb": "Eight chapters of SAD theory with worked examples and diagrams — plus a consolidated mistakes-and-traps section, an all-chapter question bank and rapid revision.",
   "src": "SAD.html",
   "sha": "d2b668040b5d",
   "url": "sad/index.html",
   "groups": [
    {
     "name": "Chapters",
     "items": [
      {
       "id": "ch1",
       "title": "Chapter 1: Overview of System Analysis and Design"
      },
      {
       "id": "ch2",
       "title": "Chapter 2: Process and Conceptual Modeling"
      },
      {
       "id": "ch3",
       "title": "Chapter 3: Data and Process Modeling"
      },
      {
       "id": "ch4",
       "title": "Chapter 4: Logic Modeling"
      },
      {
       "id": "ch5",
       "title": "Chapter 5: Object Modeling"
      },
      {
       "id": "ch6",
       "title": "Chapter 6: System Analysis"
      },
      {
       "id": "ch7",
       "title": "Chapter 7: Systems Design"
      },
      {
       "id": "ch8",
       "title": "Chapter 8: System Implementation"
      }
     ]
    },
    {
     "name": "Exam prep & revision",
     "items": [
      {
       "id": "mistakes",
       "title": "Common Mistakes & Exam Traps (Consolidated)"
      },
      {
       "id": "qbank",
       "title": "Practice Question Bank (All Chapters)"
      },
      {
       "id": "revision",
       "title": "Rapid Revision Section"
      },
      {
       "id": "checklist",
       "title": "Final Exam Checklist"
      },
      {
       "id": "matrix",
       "title": "Syllabus Coverage Matrix"
      },
      {
       "id": "outcomes",
       "title": "Learning-Outcome Alignment"
      },
      {
       "id": "report",
       "title": "Final Quality Report"
      }
     ]
    }
   ]
  },
  {
   "id": "ai",
   "title": "BIT 353 — Artificial Intelligence",
   "code": "AI",
   "color": "#a78bfa",
   "monogram": "AI",
   "blurb": "Seven topics — agents, problem solving, searching, knowledge representation, ML, neural nets and NLP — with worked examples, a formula sheet, a practice bank and a final question bank.",
   "src": "bit353-ai-master-guide.html",
   "sha": "b9c53e0f1365",
   "url": "ai/index.html",
   "groups": [
    {
     "name": "Topics",
     "items": [
      {
       "id": "t1",
       "title": "Introduction to Artificial Intelligence"
      },
      {
       "id": "t2",
       "title": "Intelligent Agent"
      },
      {
       "id": "t3",
       "title": "Problem Solving"
      },
      {
       "id": "t4",
       "title": "Searching Techniques"
      },
      {
       "id": "t5",
       "title": "Knowledge Representation"
      },
      {
       "id": "t6",
       "title": "Machine Learning"
      },
      {
       "id": "t7",
       "title": "Applications of Artificial Intelligence"
      }
     ]
    },
    {
     "name": "Exam prep & revision",
     "items": [
      {
       "id": "matrix",
       "title": "Syllabus Coverage Matrix"
      },
      {
       "id": "outcomes",
       "title": "Learning-Outcome Alignment"
      },
      {
       "id": "audit",
       "title": "Final Self-Audit & Quality Report"
      },
      {
       "id": "practice",
       "title": "Practice Problem Bank"
      },
      {
       "id": "formulas",
       "title": "Consolidated Formula & Algorithm Reference"
      },
      {
       "id": "revision",
       "title": "Final Master Revision"
      },
      {
       "id": "bank",
       "title": "Final Question Bank"
      }
     ]
    }
   ]
  },
  {
   "id": "technopreneurship",
   "title": "Technopreneurship",
   "code": "TECHNO",
   "color": "#f59e0b",
   "monogram": "TP",
   "blurb": "Eight core topics from innovation to raising capital, plus additional topics 9–12, worked examples, a question bank and past-board patterns.",
   "src": "techno.html",
   "sha": "a09c1599a6ae",
   "url": "technopreneurship/index.html",
   "groups": [
    {
     "name": "Topics",
     "items": [
      {
       "id": "intro",
       "title": "Introduction — Technopreneurship"
      },
      {
       "id": "t1",
       "title": "Topic 1 — Innovation and Ideas"
      },
      {
       "id": "t2",
       "title": "Topic 2 — Value Proposition"
      },
      {
       "id": "t3",
       "title": "Topic 3 — Customers"
      },
      {
       "id": "t4",
       "title": "Topic 4 — Competitive Advantage and Markets"
      },
      {
       "id": "t5",
       "title": "Topic 5 — Introduction to Intellectual Property"
      },
      {
       "id": "t6",
       "title": "Topic 6 — Execution and Business Plan"
      },
      {
       "id": "t7",
       "title": "Topic 7 — Financial Analysis and Accounting Basics"
      },
      {
       "id": "t8",
       "title": "Topic 8 — Raising Capital"
      },
      {
       "id": "add-header",
       "title": "Additional Topics 9–12"
      },
      {
       "id": "t9",
       "title": "Topic 9 — The Product or Service"
      },
      {
       "id": "t10",
       "title": "Topic 10 — IT Business Development Models"
      },
      {
       "id": "t11",
       "title": "Topic 11 — Ethics and Social Responsibility"
      },
      {
       "id": "t12",
       "title": "Topic 12 — Globalization"
      }
     ]
    },
    {
     "name": "Exam prep & revision",
     "items": [
      {
       "id": "revision",
       "title": "Final Master Revision"
      },
      {
       "id": "qbank",
       "title": "Final Question Bank"
      },
      {
       "id": "pbank",
       "title": "Final Practice Bank"
      },
      {
       "id": "matrix",
       "title": "Final Syllabus Coverage Matrix"
      }
     ]
    }
   ]
  }
 ],
 "updated": "September 17, 2026"
};
